services:
  # ─── PHP natif (projet racine) ───────────────────────────
  php:
    build: .
    container_name: php_82
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  # ─── Base de données MySQL ─────────────────────────────────────
  db:
    image: mysql:8.0
    container_name: mysql_8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ACA
      MYSQL_USER: zou
      MYSQL_PASSWORD: aca2026
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
  # ─── phpMyAdmin ────────────────────────────────────────────────
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: zou
      MYSQL_ROOT_PASSWORD: aca2026
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql_data:
